import type { Metadata } from "next";

import {
  CssBaseline,
} from '@mui/material';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import PageContainer from '@/components/PageContainer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <PageContainer>
          {children}
        </PageContainer>
      </body>
    </html>
  );
}
